/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './header/header.component.ngfactory';
import * as i3 from './header/header.component';
import * as i4 from './home/home.component.ngfactory';
import * as i5 from './home/home.component';
import * as i6 from './home/home.service';
import * as i7 from './app.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-header',([] as any[]),
      (null as any),(null as any),(null as any),i2.View_HeaderComponent_0,i2.RenderType_HeaderComponent)),
      i1.ɵdid(114688,(null as any),0,i3.HeaderComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,
          (null as any),(null as any),1,'app-home',([] as any[]),(null as any),(null as any),
          (null as any),i4.View_HomeComponent_0,i4.RenderType_HomeComponent)),i1.ɵdid(114688,
          (null as any),0,i5.HomeComponent,[i6.HomeService],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
        _ck(_v,4,0);
      },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i7.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i7.AppComponent> = i1.ɵccf('app-root',
    i7.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3d1dHRoaW5hbi9Xb3Jrc3BhY2UvQW5ndWxhcjIvcmF0ZG9yYS9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvd3V0dGhpbmFuL1dvcmtzcGFjZS9Bbmd1bGFyMi9yYXRkb3JhL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL3d1dHRoaW5hbi9Xb3Jrc3BhY2UvQW5ndWxhcjIvcmF0ZG9yYS9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3d1dHRoaW5hbi9Xb3Jrc3BhY2UvQW5ndWxhcjIvcmF0ZG9yYS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxuPGFwcC1ob21lPjwvYXBwLWhvbWU+IiwiPGFwcC1yb290PjwvYXBwLXJvb3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTthQUFBO1VBQUEsZUFBeUIsdUNBQ3pCO1VBQUE7VUFBQSwyRUFBQTtVQUFBOztRQURBO1FBQ0E7Ozs7b0JDREE7TUFBQTthQUFBOzs7OyJ9
